#!/bin/sh

case "$(uname -s)" in
  Darwin) GOOS=darwin ;;
  FreeBSD) GOOS=freebsd ;;
  OpenBSD) GOOS=openbsd ;;
  Linux) GOOS=linux ;;
  CYGWIN*|MINGW32*|MSYS*) GOOS=windows ;;
  *)
    echo "error: unknown arch"
    echo "please add it to: https://github.com/jbenet/go-env-sh"
    exit 1
    ;;
esac

case $(uname -m) in
  amd64) GOARCH=amd64 ;;
  x86_64) GOARCH=amd64 ;;
  i686) GOARCH=386 ;;
  i686) GOARCH=386 ;;
  arm) GOARCH=arm GOARM=7 ;;
  *)
    echo "error: unknown arch"
    echo "please add it to: https://github.com/jbenet/go-env-sh"
    exit 1
    ;;
esac

echo "$GOOS-$GOARCH"
